---
- name: mkdir build
  file: path=/opt/local/flatbuffers  state=directory  owner={{ansible_user_id}}  group={{ansible_user_gid}}

- name: Flatbuffers repository
  git: repo=https://github.com/google/flatbuffers.git  version=v1.4.0  dest=/opt/local/flatbuffers.git
  register: gitclone

- name: cmake
  shell: cmake /opt/local/flatbuffers.git   chdir=/opt/local/flatbuffers
  when: gitclone.changed

- name: make
  shell: make   chdir=/opt/local/flatbuffers
  when: gitclone.changed
