- name: mkdir build
  file: path=/opt/local/forward-epics-to-kafka  state=directory  owner={{ansible_user_id}}  group={{ansible_user_gid}}
  become: true

- name: mkdir repo
  file: path=/opt/local/forward-epics-to-kafka  state=directory  owner={{ansible_user_id}}  group={{ansible_user_gid}}
  become: true

- name: fetch repo
  git: repo={{repository_url}}  dest=/opt/local/forward-epics-to-kafka.git  version={{version}}
  register: gitclone

- name: cmake
  shell: cmake /opt/local/forward-epics-to-kafka.git   chdir=/opt/local/forward-epics-to-kafka
  when: gitclone.changed or force_recompilation

- name: make
  shell: make   chdir=/opt/local/forward-epics-to-kafka
  when: gitclone.changed or force_recompilation

- name: install service
  template:
    src: forward-epics-to-kafka.service.j2
    dest: /usr/lib/systemd/system/forward-epics-to-kafka.service
    mode: u=rw,g=rw,o=r
  become: true
