---
- include_vars: forward-epics-to-kafka.yml

- name: Install dep cmake
  yum: name=cmake  state=latest
  become: true

- name: Fetch code...
  git: repo={{repository_url}}  dest=/opt/local/forward-epics-to-kafka.git  version={{version}}  depth=1

- name: mkdir build
  file: path=/opt/local/forward-epics-to-kafka  state=directory  owner={{ansible_user_id}}  group={{ansible_user_gid}}

- name: cmake
  shell: cmake /opt/local/forward-epics-to-kafka.git   chdir=/opt/local/forward-epics-to-kafka

- name: make
  shell: make   chdir=/opt/local/forward-epics-to-kafka
