---
# This expects  ./roles/forward_epics_to_kafka/files/jansson-2.7.tar.gz

- include_vars: jansson.yml

- name: mkdir build
  file: path={{dbuild}} state=directory  owner={{ansible_user_id}}  group={{ansible_user_gid}}
  become: yes

- name: mkdir install
  file: path={{dinstall}} state=directory

- name: unpack
  unarchive: src={{N}}.tar.gz  dest={{dbuild}}/..

- name: configure
  shell: /{{dbuild}}/../{{N}}/configure --prefix=`cd {{dinstall}}; pwd`  chdir={{dbuild}}

- name: make
  shell: make -j 4  chdir={{dbuild}}

- name: make install
  shell: make install   chdir={{dbuild}}
