---
- name: Prepare build directory
  file: path={{path_libs_build}} state=directory  owner={{ansible_user_id}}  group={{ansible_user_gid}}
  become: yes

#- include: jansson.yml
- include: jansson_yum.yml

- include: cmake.yml

- include: rdkafka.yml
  tags:
  - rdkafka

- include: flatbuffers.yml
  tags:
  - flatbuffers

- include: forward-epics-to-kafka.yml
  tags:
  - fwd
